# First database operation - CRUD operation... 
# crear_producto(producto) receives a Producto object from the class
from app.database import conectar
from app.modelos import Producto

#----------------------
# CREATE - POST /items
# ---------------------
def crear_producto(producto):
    """Guarda un nuevo producto en la base de datos"""
    conexion = conectar()
    cursor = conexion.cursor()

# Insert the data from the Product object into the products table
    cursor.execute("""INSERT INTO productos (nombre, descripcion, 
        categoria, precio)
        VALUES (?, ?, ?, ?)""",
        (producto.nombre,
        producto.descripcion,
        producto.categoria,
        producto.precio))
    
# Save the changes in SQLite
    conexion.commit()
# Retrieve the ID automatically generated by SQLite
    producto.id = cursor.lastrowid
# Closes the connection when the operation finishes
    conexion.close()

    return producto

#-------------------
# READ - GET /items
#-------------------
def listar_productos():
    """Devuelve todos los productos guardados en la base de datos"""
    conexion = conectar()
    cursor = conexion.cursor()

    cursor.execute("""SELECT id, nombre, descripcion, categoria, 
        precio FROM productos""")

    filas = cursor.fetchall()
    conexion.close()

    productos = []

# Convert each SQLite row into a Product object
    for fila in filas:
        producto = Producto(nombre=fila[1],
                            descripcion=fila[2],
                            categoria=fila[3],
                            precio=fila[4],
                            id=fila[0])
# Converts the object into a dictionary to return it as JSON
        productos.append(producto.to_dict())
    return productos

#------------------------
# READ - GET /items/{id}
#------------------------
def obtener_producto(id):
    """Busca un producto por su ID"""
    conexion = conectar()
    cursor = conexion.cursor()
# Search only for the product whose ID matches
    cursor.execute("""SELECT id, nombre, descripcion, categoria,
        precio FROM productos WHERE id = ?""", (id,))
    fila = cursor.fetchone()
    conexion.close()
# If no record with that ID exists, it returns None
    if fila is None:
        return None

    producto = Producto(nombre=fila[1],
                        descripcion=fila[2],
                        categoria=fila[3],
                        precio=fila[4],
                        id=fila[0])
    return producto.to_dict()

#---------------------------
# UPDATE - PUT /items /{id}
#---------------------------
def actualizar_producto(id, producto):
    """Actualiza los datos de un producto existente"""
    conexion = conectar()
    cursor = conexion.cursor()

# Update the product that matches the received ID
    cursor.execute("""UPDATE productos
        SET nombre = ?,
        descripcion = ?,
        categoria = ?,
        precio = ?
        WHERE id = ? """, # makes sure we update only the requested product
        (producto.nombre,
        producto.descripcion,
        producto.categoria,
        producto.precio,
        id))

    conexion.commit()

# rowcount indicates how many rows were modified
# Return 404 
    filas_modificadas = cursor.rowcount 

    conexion.close()

# If no row was modified, the ID does not exist
    if filas_modificadas == 0:
        return None

    producto.id = id
    return producto.to_dict()

#------------------------------
# DELETE - DELETE /items /{id}
#------------------------------
def eliminar_producto(id):
    """Elimina un producto de la base de datos por su ID"""
    conexion = conectar()
    cursor = conexion.cursor()

# Deletes only the product that matches the received ID
    cursor.execute("""DELETE FROM productos WHERE id = ?""",
                   (id,))
    conexion.commit()

# rowcount indicates how many rows were deleted
    filas_eliminadas = cursor.rowcount

    conexion.close()

# If no rows were deleted, the ID did not exist
    if filas_eliminadas == 0:
        return False

    return True
